version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/donation-storage-client

hooks:
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
